const prompts = [
  // Hypixel-style simple themes
  "Castle",
  "Avocado",
  "Pancake",
  "Wolf",
  "Skyscraper",
  "Chocolate",
  "Tree",
  "Hotdog",
  "Cow",
  "Temple",
  "Waffle",
  "Dragon",
  "Alien",
  "Plane",
  "Garden",
  "Robot",
  "Spaceship",
  "Beach",
  "Cave",
  "Rainbow",

  // Reddit community-style creative themes
  "Steampunk Airship",
  "Floating Island",
  "Cyberpunk Street",
  "Underwater City",
  "Ancient Ruins",
  "Fantasy Tavern",
  "Desert Bazaar",
  "Snowy Village",
  "Jungle Temple",
  "Volcanic Fortress",
  "Pirate Cove",
  "Magic Library",
  "Space Colony",
  "Mushroom Forest",
  "Hidden Base",
  "Crystal Cave",
  "Witch Hut",
  "Sky Castle",
  "Treehouse Village"
];

